
MAX_SITES = 30
SEARCH_MULTIPLIER = 2
TIMEOUT_SECONDS = 8
ENABLE_TIMEOUT = True
ENABLE_USER_AGENT = True
ENABLE_PARALLEL = True
MAX_WORKERS = 5
SHOW_DETAILED_PROGRESS = False
SHOW_FAILURE_ANALYSIS = False
MIN_TEXT_LENGTH = 200
MAX_FAILURE_DISPLAY = 10
SEARCH_DOMAINS = ['blog.naver.com', 'news.naver.com', 'youtube.com']